### ISSUE TITLE
No module named statistics

### ISSUE THREAD

**Issue by MasterCATZ** [gandalf15/HX711#38]
sudo python example.py 
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from hx711 import HX711  # import the class HX711
  File "/home/pi/git/HX711/HX711_Python3/hx711.py", line 6, in <module>
    import statistics as stat
ImportError: No module named statistics

fresh pi install

**Comment by gandalf15** [comment]
Hi.
you have to use Python3.
So the command is `$ sudo python3 example.py`
